### ISSUE TITLE
User-Agent parse error

### ISSUE THREAD

**Issue by zorelworld** [invernizzi/scapy-http#14] opened 2015-09-02 10:21 UTC
pkt[http.HTTPRequest].Host  is right.But pkt[http.HTTPRequest].User-Agent is wrong.if my field have '-',the error will Appear

**Comment by invernizzi** [comment] 2015-09-14 06:12
Hi,
thanks for the bug report. I tried to reproduce it, using a User-Agent with a '-' in it, but I do not get any parsing error. Would you mind giving me an example, or more information about the bug?
Thanks!

**Comment by invernizzi** [comment] 2015-11-02 04:23
I'm closing this because I couldn't reproduce it. Please, reopen this bug if needed.

**Closed by invernizzi** 2015-11-02 04:23 UTC

**Comment by jgrover** [comment] 2016-12-07 14:59
Also encountering this error, where an error appears when a hyphen is used.  Got around it by just doing a regex search against the full header. Using the latest scapy3k package on Python 3.5.1 / Ubuntu 16.04.

**Comment by jgrover** [comment] 2016-12-07 16:43
Dug a little further with this.  The header dictionary is formed properly by the scapy_http library, but the problem exists in the scapy direct dictionary structure/method.
